export function randomInt(n){if(!Number.isInteger(n)||n<1||n>4294967296)throw Error('invalid range');const a=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%n;}
export function deck(packs=1){const d=[];for(let p=0;p<packs;p++)for(let s=0;s<4;s++)for(let r=2;r<=14;r++)d.push({r,s});for(let i=d.length-1;i>0;i--){const j=randomInt(i+1);[d[i],d[j]]=[d[j],d[i]];}return d;}
export function bj(cards){let n=cards.reduce((a,c)=>a+(c.r===14?11:Math.min(c.r,10)),0),aces=cards.filter(c=>c.r===14).length;while(n>21&&aces-->0)n-=10;return n;}
export const baccaratScore=cs=>cs.reduce((a,c)=>a+(c.r===14?1:c.r>=10?0:c.r),0)%10;
export function baccarat(d){const p=[d.pop()],b=[d.pop()];p.push(d.pop());b.push(d.pop());let ps=baccaratScore(p),bs=baccaratScore(b);if(ps<8&&bs<8){let third=null;if(ps<=5){const c=d.pop();p.push(c);third=baccaratScore([c]);}if(third===null?bs<=5:bs<=2||(bs===3&&third!==8)||(bs===4&&third>=2&&third<=7)||(bs===5&&third>=4&&third<=7)||(bs===6&&third>=6&&third<=7))b.push(d.pop());}return {p,b,ps:baccaratScore(p),bs:baccaratScore(b)};}
export const names=['ハイカード','ワンペア','ツーペア','スリーカード','ストレート','フラッシュ','フルハウス','フォーカード','ストレートフラッシュ'];
function five(cs){const rs=cs.map(c=>c.r).sort((a,b)=>b-a),freq={};rs.forEach(r=>freq[r]=(freq[r]||0)+1);const groups=Object.entries(freq).map(([r,n])=>[n,+r]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]);const flush=cs.every(c=>c.s===cs[0].s);const unique=[...new Set(rs)];let straight=unique.length===5&&unique[0]-unique[4]===4?unique[0]:unique.join()==='14,5,4,3,2'?5:0;let v;if(straight&&flush)v=[8,straight];else if(groups[0][0]===4)v=[7,...groups.map(g=>g[1])];else if(groups[0][0]===3&&groups[1][0]===2)v=[6,...groups.map(g=>g[1])];else if(flush)v=[5,...rs];else if(straight)v=[4,straight];else if(groups[0][0]===3)v=[3,...groups.map(g=>g[1])];else if(groups[0][0]===2&&groups[1][0]===2)v=[2,...groups.map(g=>g[1])];else if(groups[0][0]===2)v=[1,...groups.map(g=>g[1])];else v=[0,...rs];return {category:v[0],score:Array.from({length:6},(_,i)=>v[i]||0).reduce((a,n)=>a*15+n,0)};}
export function rank(cs){let best={score:-1};for(let a=0;a<cs.length-4;a++)for(let b=a+1;b<cs.length-3;b++)for(let c=b+1;c<cs.length-2;c++)for(let d=c+1;d<cs.length-1;d++)for(let e=d+1;e<cs.length;e++){const r=five([cs[a],cs[b],cs[c],cs[d],cs[e]]);if(r.score>best.score)best=r;}return best;}
export function equity(hand,board,trials=100){const known=new Set([...hand,...board].map(c=>c.s*20+c.r));let wins=0;for(let i=0;i<trials;i++){const d=deck().filter(c=>!known.has(c.s*20+c.r));const opp=[d.pop(),d.pop()],table=[...board];while(table.length<5)table.push(d.pop());const a=rank([...hand,...table]).score,b=rank([...opp,...table]).score;wins+=a>b?1:a===b?.5:0;}return wins/trials;}
export const red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
export function rouletteReturn(n,type,stake,number){if(type==='number')return n===number?stake*36:0;if(n===0)return 0;const win=type==='red'?red.has(n):type==='black'?!red.has(n):type==='even'?n%2===0:type==='odd'?n%2===1:type==='low'?n<=18:n>=19;return win?stake*2:0;}
export function tokyoDate(date=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(date);}
